version: '3.2'
services:
  zlp-prom-pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
  zlp-prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    extra_hosts:
      - "host.docker.internal:host-gateway" #for linux
  zlp-grafana:
    image: grafana/grafana
    depends_on:
      - zlp-prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
